name: Jira Issue Status Change Trigger

on:
  workflow_dispatch:
  repository_dispatch:
    types: jira-update

jobs:
  handleJiraUpdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build
        run: |
          echo "Build initiated due to Jira status change to Done!"
        # Add your build commands here
