name: demo_workflow_1.0.0
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  hello:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello-World"
        shell: bash
