name: My Workflow on Jira Done Transition

on:
  repository_dispatch:
    types: [my-event-name]

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # Add other steps as per your requirement
    - name: Do something
      run: echo "JIRA issue status was updated!"
