name: Jira Trigger

on:
  workflow_dispatch:
  repository_dispatch:
    types: jira-issue-updated

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run your task
      run: |
        echo "Jira issue updated!"
        # Your commands here
