name: Hello world workflow

on:
push:
	branches:
		- main
pull_request:
		branches:
			- main
	workflow_disptach

jobs:
	hello:
	runs-on: ubuntu-latest
	steps:
		- uses: actions/checkout@v2
		- name: hello world
		run: echo "Hello-World"
		shell: bash

	goodbye:
	runs-on: ubuntu-latest
	steps:
		- name: goodbye
		run: echo "goodbye!"
		shell: bash


