name: Jira Triggered Workflow

on:
  workflow_dispatch:
  repository_dispatch:
    types: jira-status-change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run some job
      run: echo "Jira status changed!"
