name: Jira-Triggered Build

on:
  repository_dispatch:
    types: [jira-status-changed-to-done]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build
      run: |
        echo "Build initiated due to Jira status change to Done!"
        # Add your build commands here
