name: JIRA Triggered Workflow
on:
  repository_dispatch:
    types: [jira-update]

jobs:
  handle-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Do something
      run: echo "JIRA issue status was updated!"
